In [227]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [351]:
df = pd.read_excel('Test_dataset.xlsx','Put-Call_TS',skiprows=1)
df.head()

Unnamed: 0  2020-08-10 00:00:00  ...  2020-08-14 00:00:00  2020-08-15 00:00:00
0     AC3235                 0.80  ...             0.901211             0.898368
1     AC3236                 0.86  ...             1.017042             1.029258
2     AC3237                 0.93  ...                  NaN             1.181962
3     AC3238                 1.09  ...             1.461062             1.531000
4     AC3239                  NaN  ...             1.615504             1.705519

[5 rows x 7 columns]

In [352]:
test=df.rename(columns={'Unnamed: 0': "Stock Index"})
test.head()

Stock Index  2020-08-10 00:00:00  ...  2020-08-14 00:00:00  2020-08-15 00:00:00
0      AC3235                 0.80  ...             0.901211             0.898368
1      AC3236                 0.86  ...             1.017042             1.029258
2      AC3237                 0.93  ...                  NaN             1.181962
3      AC3238                 1.09  ...             1.461062             1.531000
4      AC3239                  NaN  ...             1.615504             1.705519

[5 rows x 7 columns]

In [353]:
SI=test['Stock Index']
test=test.drop(['Stock Index'],axis=1)

In [ ]:
'''test=pd.DataFrame(df['Stock Index'])
test['d1']=df[df.columns[1]]
test['d2']=df[df.columns[2]]
test['d3']=df[df.columns[3]]
test['d4']=df[df.columns[4]]
test['d5']=df[df.columns[5]]
test['d6']=df[df.columns[6]]
test.head()'''

In [354]:
test=test.T
test.head()

0         1         2     ...      3328      3329      3330
2020-08-10 00:00:00  0.800000  0.860000  0.930000  ...  0.670000  0.790000  0.740000
2020-08-11 00:00:00  0.660000  0.732000  0.816000  ...  0.504000  0.648000  0.588000
2020-08-12 00:00:00  0.772400  0.854480  0.950240  ...  0.594560  0.758720  0.690320
2020-08-13 00:00:00  0.983224  1.086645  1.207302  ...  0.759146  0.965987  0.879803
2020-08-14 00:00:00  0.901211  1.017042       NaN  ...  0.650243  0.881906  0.785380

[5 rows x 3331 columns]

In [355]:
test=test.interpolate(method ='linear', limit_direction ='backward')
test=test.interpolate(method ='linear', limit_direction ='forward')
test

0         1         2     ...      3328      3329      3330
2020-08-10 00:00:00  0.800000  0.860000  0.930000  ...  0.670000  0.790000  0.740000
2020-08-11 00:00:00  0.660000  0.732000  0.816000  ...  0.504000  0.648000  0.588000
2020-08-12 00:00:00  0.772400  0.854480  0.950240  ...  0.594560  0.758720  0.690320
2020-08-13 00:00:00  0.983224  1.086645  1.207302  ...  0.759146  0.965987  0.879803
2020-08-14 00:00:00  0.901211  1.017042  1.194632  ...  0.650243  0.881906  0.785380
2020-08-15 00:00:00  0.898368  1.029258  1.181962  ...  0.614775  0.876553  0.767479

[6 rows x 3331 columns]

In [356]:
test.T.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3331 entries, 0 to 3330
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   2020-08-10 00:00:00  3331 non-null   float64
 1   2020-08-11 00:00:00  3331 non-null   float64
 2   2020-08-12 00:00:00  3331 non-null   float64
 3   2020-08-13 00:00:00  3331 non-null   float64
 4   2020-08-14 00:00:00  3331 non-null   float64
 5   2020-08-15 00:00:00  3331 non-null   float64
dtypes: float64(6)
memory usage: 156.3 KB


In [357]:
test=test.T
test.shape

(3331, 6)

In [358]:
#test=pd.concat([SI,test],axis=1)
test.head()

2020-08-10  ...  2020-08-15
0       0.800  ...    0.898368
1       0.860  ...    1.029258
2       0.930  ...    1.181962
3       1.090  ...    1.531000
4       1.104  ...    1.705519

[5 rows x 6 columns]

In [359]:
print(test.shape)
test.info()

(3331, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3331 entries, 0 to 3330
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   2020-08-10 00:00:00  3331 non-null   float64
 1   2020-08-11 00:00:00  3331 non-null   float64
 2   2020-08-12 00:00:00  3331 non-null   float64
 3   2020-08-13 00:00:00  3331 non-null   float64
 4   2020-08-14 00:00:00  3331 non-null   float64
 5   2020-08-15 00:00:00  3331 non-null   float64
dtypes: float64(6)
memory usage: 156.3 KB


**model**

In [360]:

# split a univariate sequence into samples
def split_sequence(data, n_steps):
  
  X, y = list(), list()
  for k in range(data.shape[0]):
    sequence = data.iloc[k,:]
    for i in range(len(sequence)):
      # find the end of this pattern
      end_ix = i + n_steps
      # check if we are beyond the sequence
      if end_ix > len(sequence)-1:
        break
      # gather input and output parts of the pattern
      seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
      X.append(seq_x)
      y.append(seq_y)
  return np.array(X), np.array(y)

In [361]:
X,y = split_sequence(test,4)
X

array([[0.8       , 0.66      , 0.7724    , 0.983224  ],
       [0.66      , 0.7724    , 0.983224  , 0.90121088],
       [0.86      , 0.732     , 0.85448   , 1.0866448 ],
       ...,
       [0.648     , 0.75872   , 0.9659872 , 0.88190566],
       [0.74      , 0.588     , 0.69032   , 0.8798032 ],
       [0.588     , 0.69032   , 0.8798032 , 0.78537958]])

In [362]:
X.shape

(6662, 4)

In [363]:
y.shape
y

array([0.90121088, 0.89836829, 1.01704218, ..., 0.8765534 , 0.78537958,
       0.76747893])

In [364]:
from keras.models import Sequential
from keras.layers import Dense,LSTM
from keras.layers import Dropout

In [365]:
X = X.reshape((X.shape[0], X.shape[1], 1))

In [367]:
model = Sequential()
model.add(LSTM(40, activation='relu', return_sequences=True,input_shape=(4, 1)))
model.add(Dropout(0.2))
model.add(LSTM(40, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_21"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_54 (LSTM)               (None, 4, 40)             6720      
_________________________________________________________________
dropout_35 (Dropout)         (None, 4, 40)             0         
_________________________________________________________________
lstm_55 (LSTM)               (None, 40)                12960     
_________________________________________________________________
dropout_36 (Dropout)         (None, 40)                0         
_________________________________________________________________
dense_18 (Dense)             (None, 1)                 41        
Total params: 19,721
Trainable params: 19,721
Non-trainable params: 0
_________________________________________________________________


In [368]:
model.fit(X, y, epochs=20, verbose=1)

Epoch 1/20
209/209 [==============================] - 1s 5ms/step - loss: 0.2727
Epoch 2/20
209/209 [==============================] - 1s 5ms/step - loss: 0.0365
Epoch 3/20
209/209 [==============================] - 1s 4ms/step - loss: 0.0284
Epoch 4/20
209/209 [==============================] - 1s 4ms/step - loss: 0.0228
Epoch 5/20
209/209 [==============================] - 1s 4ms/step - loss: 0.0220
Epoch 6/20
209/209 [==============================] - 1s 5ms/step - loss: 0.0208
Epoch 7/20
209/209 [==============================] - 1s 5ms/step - loss: 0.0196
Epoch 8/20
209/209 [==============================] - 1s 4ms/step - loss: 0.0192
Epoch 9/20
209/209 [==============================] - 1s 5ms/step - loss: 0.0185
Epoch 10/20
209/209 [==============================] - 1s 4ms/step - loss: 0.0167
Epoch 11/20
209/209 [==============================] - 1s 5ms/step - loss: 0.0161
Epoch 12/20
209/209 [==============================] - 1s 4ms/step - loss: 0.0160
Epoch 13/20
209/209 [====

In [369]:
X_t = test.iloc[:,2:].values
test.head()

2020-08-10  ...  2020-08-15
0       0.800  ...    0.898368
1       0.860  ...    1.029258
2       0.930  ...    1.181962
3       1.090  ...    1.531000
4       1.104  ...    1.705519

[5 rows x 6 columns]

In [370]:
X_t.shape

(3331, 4)

In [371]:
X_t

array([[0.7724    , 0.983224  , 0.90121088, 0.89836829],
       [0.85448   , 1.0866448 , 1.01704218, 1.02925766],
       [0.95024   , 1.2073024 , 1.19463216, 1.18196192],
       ...,
       [0.59456   , 0.7591456 , 0.65024307, 0.61477467],
       [0.75872   , 0.9659872 , 0.88190566, 0.8765534 ],
       [0.69032   , 0.8798032 , 0.78537958, 0.76747893]])

In [373]:
X_t = X_t.reshape(X_t.shape[0],4,1)
X_t.shape

(3331, 4, 1)

In [219]:
model.predict(X_t)

array([[1.2069603],
       [1.3782158],
       [1.5451423],
       ...,
       [0.8452974],
       [1.1786172],
       [1.0378606]], dtype=float32)

In [374]:
model.predict(X_t)

array([[1.0835873 ],
       [1.2203355 ],
       [1.3956534 ],
       ...,
       [0.73761004],
       [1.0576675 ],
       [0.9280465 ]], dtype=float32)

In [375]:
test['2020-08-16 00:00:00'] = model.predict(X_t)

In [376]:
test.shape

(3331, 7)

In [379]:
sub=pd.concat([SI,test['2020-08-16 00:00:00']],axis=1)
sub.head()

Stock Index  2020-08-16 00:00:00
0      AC3235             1.083587
1      AC3236             1.220335
2      AC3237             1.395653
3      AC3238             1.787674
4      AC3239             1.965518

In [380]:
sub.to_csv('pcr2.csv')

**verification**

In [378]:
pd.concat([SI,test],axis=1)

Stock Index  2020-08-10 00:00:00  ...  2020-08-15 00:00:00  2020-08-16 00:00:00
0         AC3235                0.800  ...             0.898368             1.083587
1         AC3236                0.860  ...             1.029258             1.220335
2         AC3237                0.930  ...             1.181962             1.395653
3         AC3238                1.090  ...             1.531000             1.787674
4         AC3239                1.104  ...             1.705519             1.965518
...          ...                  ...  ...                  ...                  ...
3326      AD2734                0.860  ...             1.029258             1.220335
3327      AD2735                0.640  ...             0.549330             0.668787
3328      AD2736                0.670  ...             0.614775             0.737610
3329      AD2737                0.790  ...             0.876553             1.057667
3330      AD2738                0.740  ...             0.767479             0.928047

[3331 rows x 8 columns]

In [392]:
from sklearn.metrics import mean_squared_error ,explained_variance_score
explained_variance_score(test[test.columns[1]],test[test.columns[2]])

0.9786488728471555

In [393]:
explained_variance_score(test[test.columns[2]],test[test.columns[3]])

0.9306598474582783

In [394]:
from sklearn.metrics import mean_squared_error
explained_variance_score(test[test.columns[3]],test[test.columns[4]])

0.9842037608759393

In [395]:
explained_variance_score(test[test.columns[4]],test[test.columns[5]])

0.9837561859694512

In [396]:
explained_variance_score(test[test.columns[5]],test[test.columns[6]])

0.9847759278853084

In [400]:
explained_variance_score(test[test.columns[0]],test[test.columns[1]])

0.9369449687760846

In [384]:
test.columns[5]

datetime.datetime(2020, 8, 15, 0, 0)

In [385]:
test[test.columns[5]]

0       0.898368
1       1.029258
2       1.181962
3       1.531000
4       1.705519
          ...   
3326    1.029258
3327    0.549330
3328    0.614775
3329    0.876553
3330    0.767479
Name: 2020-08-15 00:00:00, Length: 3331, dtype: float64

In [399]:
test.columns[0]

datetime.datetime(2020, 8, 10, 0, 0)